services:
  app:
    image: adminka-app
    volumes:
      # Монтируем папку с базой данных
      - /home/leo/Admin:/app  # Путь на хосте: /home/leo/Admin
    ports:
      - "9090:8000"
    restart: always
