version: '3.8'

services:
  app:
    build: .
    volumes:
      - /home/leo/24.10.24/Adminka:/app  # Монтируем локальную директорию в контейнер
      - /home/leo/24.10.24/Adminka/media/media:/app/media
    ports:
      - "9090:8000"  # Пример порта, измените по необходимости