
services:
  app:
    build: .
    volumes:
 # Монтируем локальную директорию в контейнер
      - my_photos_volume:/app/media
    ports:
      - "9090:8000"  # Пример порта, измените по необходимости

volumes:
  my_photos_volume: