version: '3.8'

services:
  app:
    build: .
    volumes:
      - /home/leo/Admin:/app  # Монтируем локальную директорию в контейнер
      - /home/leo/Admin/media/media:/app/media
    ports:
      - "9090:8000"  # Пример порта, измените по необходимости