# Generated by Django 5.1.2 on 2024-11-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_category_alter_news_options_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
